/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhoRouteImport } from './routes/trabalho'
import { Route as Talk2buyRouteImport } from './routes/talk2buy'
import { Route as SympliceRouteImport } from './routes/symplice'
import { Route as SolidRouteImport } from './routes/solid'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as NatraveRouteImport } from './routes/natrave'
import { Route as MilgrowsRouteImport } from './routes/milgrows'
import { Route as MetodosRouteImport } from './routes/metodos'
import { Route as MaxiRouteImport } from './routes/maxi'
import { Route as MarcoBoniRouteImport } from './routes/marco-boni'
import { Route as LivinRouteImport } from './routes/livin'
import { Route as KmillionRouteImport } from './routes/kmillion'
import { Route as KapyiRouteImport } from './routes/kapyi'
import { Route as EvidiveRouteImport } from './routes/evidive'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodosIndexRouteImport } from './routes/metodos.index'
import { Route as MetodosSistemaDeConteudoRouteImport } from './routes/metodos.sistema-de-conteudo'
import { Route as MetodosPresencaDigitalRouteImport } from './routes/metodos.presenca-digital'
import { Route as MetodosMidiaOohRouteImport } from './routes/metodos.midia-ooh'
import { Route as MetodosMidiaImpressaRouteImport } from './routes/metodos.midia-impressa'
import { Route as MetodosMarketingDeInfluenciaRouteImport } from './routes/metodos.marketing-de-influencia'
import { Route as MetodosEstruturacaoDeMarcaRouteImport } from './routes/metodos.estruturacao-de-marca'
import { Route as BrandBrandIdRouteImport } from './routes/brand.$brandId'

const TrabalhoRoute = TrabalhoRouteImport.update({
  id: '/trabalho',
  path: '/trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const Talk2buyRoute = Talk2buyRouteImport.update({
  id: '/talk2buy',
  path: '/talk2buy',
  getParentRoute: () => rootRouteImport,
} as any)
const SympliceRoute = SympliceRouteImport.update({
  id: '/symplice',
  path: '/symplice',
  getParentRoute: () => rootRouteImport,
} as any)
const SolidRoute = SolidRouteImport.update({
  id: '/solid',
  path: '/solid',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const NatraveRoute = NatraveRouteImport.update({
  id: '/natrave',
  path: '/natrave',
  getParentRoute: () => rootRouteImport,
} as any)
const MilgrowsRoute = MilgrowsRouteImport.update({
  id: '/milgrows',
  path: '/milgrows',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosRoute = MetodosRouteImport.update({
  id: '/metodos',
  path: '/metodos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxiRoute = MaxiRouteImport.update({
  id: '/maxi',
  path: '/maxi',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcoBoniRoute = MarcoBoniRouteImport.update({
  id: '/marco-boni',
  path: '/marco-boni',
  getParentRoute: () => rootRouteImport,
} as any)
const LivinRoute = LivinRouteImport.update({
  id: '/livin',
  path: '/livin',
  getParentRoute: () => rootRouteImport,
} as any)
const KmillionRoute = KmillionRouteImport.update({
  id: '/kmillion',
  path: '/kmillion',
  getParentRoute: () => rootRouteImport,
} as any)
const KapyiRoute = KapyiRouteImport.update({
  id: '/kapyi',
  path: '/kapyi',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidiveRoute = EvidiveRouteImport.update({
  id: '/evidive',
  path: '/evidive',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosIndexRoute = MetodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetodosRoute,
} as any)
const MetodosSistemaDeConteudoRoute =
  MetodosSistemaDeConteudoRouteImport.update({
    id: '/sistema-de-conteudo',
    path: '/sistema-de-conteudo',
    getParentRoute: () => MetodosRoute,
  } as any)
const MetodosPresencaDigitalRoute = MetodosPresencaDigitalRouteImport.update({
  id: '/presenca-digital',
  path: '/presenca-digital',
  getParentRoute: () => MetodosRoute,
} as any)
const MetodosMidiaOohRoute = MetodosMidiaOohRouteImport.update({
  id: '/midia-ooh',
  path: '/midia-ooh',
  getParentRoute: () => MetodosRoute,
} as any)
const MetodosMidiaImpressaRoute = MetodosMidiaImpressaRouteImport.update({
  id: '/midia-impressa',
  path: '/midia-impressa',
  getParentRoute: () => MetodosRoute,
} as any)
const MetodosMarketingDeInfluenciaRoute =
  MetodosMarketingDeInfluenciaRouteImport.update({
    id: '/marketing-de-influencia',
    path: '/marketing-de-influencia',
    getParentRoute: () => MetodosRoute,
  } as any)
const MetodosEstruturacaoDeMarcaRoute =
  MetodosEstruturacaoDeMarcaRouteImport.update({
    id: '/estruturacao-de-marca',
    path: '/estruturacao-de-marca',
    getParentRoute: () => MetodosRoute,
  } as any)
const BrandBrandIdRoute = BrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/evidive': typeof EvidiveRoute
  '/kapyi': typeof KapyiRoute
  '/kmillion': typeof KmillionRoute
  '/livin': typeof LivinRoute
  '/marco-boni': typeof MarcoBoniRoute
  '/maxi': typeof MaxiRoute
  '/metodos': typeof MetodosRouteWithChildren
  '/milgrows': typeof MilgrowsRoute
  '/natrave': typeof NatraveRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/talk2buy': typeof Talk2buyRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/metodos/estruturacao-de-marca': typeof MetodosEstruturacaoDeMarcaRoute
  '/metodos/marketing-de-influencia': typeof MetodosMarketingDeInfluenciaRoute
  '/metodos/midia-impressa': typeof MetodosMidiaImpressaRoute
  '/metodos/midia-ooh': typeof MetodosMidiaOohRoute
  '/metodos/presenca-digital': typeof MetodosPresencaDigitalRoute
  '/metodos/sistema-de-conteudo': typeof MetodosSistemaDeConteudoRoute
  '/metodos/': typeof MetodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/evidive': typeof EvidiveRoute
  '/kapyi': typeof KapyiRoute
  '/kmillion': typeof KmillionRoute
  '/livin': typeof LivinRoute
  '/marco-boni': typeof MarcoBoniRoute
  '/maxi': typeof MaxiRoute
  '/milgrows': typeof MilgrowsRoute
  '/natrave': typeof NatraveRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/talk2buy': typeof Talk2buyRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/metodos/estruturacao-de-marca': typeof MetodosEstruturacaoDeMarcaRoute
  '/metodos/marketing-de-influencia': typeof MetodosMarketingDeInfluenciaRoute
  '/metodos/midia-impressa': typeof MetodosMidiaImpressaRoute
  '/metodos/midia-ooh': typeof MetodosMidiaOohRoute
  '/metodos/presenca-digital': typeof MetodosPresencaDigitalRoute
  '/metodos/sistema-de-conteudo': typeof MetodosSistemaDeConteudoRoute
  '/metodos': typeof MetodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/evidive': typeof EvidiveRoute
  '/kapyi': typeof KapyiRoute
  '/kmillion': typeof KmillionRoute
  '/livin': typeof LivinRoute
  '/marco-boni': typeof MarcoBoniRoute
  '/maxi': typeof MaxiRoute
  '/metodos': typeof MetodosRouteWithChildren
  '/milgrows': typeof MilgrowsRoute
  '/natrave': typeof NatraveRoute
  '/sobre': typeof SobreRoute
  '/solid': typeof SolidRoute
  '/symplice': typeof SympliceRoute
  '/talk2buy': typeof Talk2buyRoute
  '/trabalho': typeof TrabalhoRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/metodos/estruturacao-de-marca': typeof MetodosEstruturacaoDeMarcaRoute
  '/metodos/marketing-de-influencia': typeof MetodosMarketingDeInfluenciaRoute
  '/metodos/midia-impressa': typeof MetodosMidiaImpressaRoute
  '/metodos/midia-ooh': typeof MetodosMidiaOohRoute
  '/metodos/presenca-digital': typeof MetodosPresencaDigitalRoute
  '/metodos/sistema-de-conteudo': typeof MetodosSistemaDeConteudoRoute
  '/metodos/': typeof MetodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/evidive'
    | '/kapyi'
    | '/kmillion'
    | '/livin'
    | '/marco-boni'
    | '/maxi'
    | '/metodos'
    | '/milgrows'
    | '/natrave'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/talk2buy'
    | '/trabalho'
    | '/brand/$brandId'
    | '/metodos/estruturacao-de-marca'
    | '/metodos/marketing-de-influencia'
    | '/metodos/midia-impressa'
    | '/metodos/midia-ooh'
    | '/metodos/presenca-digital'
    | '/metodos/sistema-de-conteudo'
    | '/metodos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/evidive'
    | '/kapyi'
    | '/kmillion'
    | '/livin'
    | '/marco-boni'
    | '/maxi'
    | '/milgrows'
    | '/natrave'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/talk2buy'
    | '/trabalho'
    | '/brand/$brandId'
    | '/metodos/estruturacao-de-marca'
    | '/metodos/marketing-de-influencia'
    | '/metodos/midia-impressa'
    | '/metodos/midia-ooh'
    | '/metodos/presenca-digital'
    | '/metodos/sistema-de-conteudo'
    | '/metodos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/evidive'
    | '/kapyi'
    | '/kmillion'
    | '/livin'
    | '/marco-boni'
    | '/maxi'
    | '/metodos'
    | '/milgrows'
    | '/natrave'
    | '/sobre'
    | '/solid'
    | '/symplice'
    | '/talk2buy'
    | '/trabalho'
    | '/brand/$brandId'
    | '/metodos/estruturacao-de-marca'
    | '/metodos/marketing-de-influencia'
    | '/metodos/midia-impressa'
    | '/metodos/midia-ooh'
    | '/metodos/presenca-digital'
    | '/metodos/sistema-de-conteudo'
    | '/metodos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EvidiveRoute: typeof EvidiveRoute
  KapyiRoute: typeof KapyiRoute
  KmillionRoute: typeof KmillionRoute
  LivinRoute: typeof LivinRoute
  MarcoBoniRoute: typeof MarcoBoniRoute
  MaxiRoute: typeof MaxiRoute
  MetodosRoute: typeof MetodosRouteWithChildren
  MilgrowsRoute: typeof MilgrowsRoute
  NatraveRoute: typeof NatraveRoute
  SobreRoute: typeof SobreRoute
  SolidRoute: typeof SolidRoute
  SympliceRoute: typeof SympliceRoute
  Talk2buyRoute: typeof Talk2buyRoute
  TrabalhoRoute: typeof TrabalhoRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalho': {
      id: '/trabalho'
      path: '/trabalho'
      fullPath: '/trabalho'
      preLoaderRoute: typeof TrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk2buy': {
      id: '/talk2buy'
      path: '/talk2buy'
      fullPath: '/talk2buy'
      preLoaderRoute: typeof Talk2buyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symplice': {
      id: '/symplice'
      path: '/symplice'
      fullPath: '/symplice'
      preLoaderRoute: typeof SympliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solid': {
      id: '/solid'
      path: '/solid'
      fullPath: '/solid'
      preLoaderRoute: typeof SolidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natrave': {
      id: '/natrave'
      path: '/natrave'
      fullPath: '/natrave'
      preLoaderRoute: typeof NatraveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milgrows': {
      id: '/milgrows'
      path: '/milgrows'
      fullPath: '/milgrows'
      preLoaderRoute: typeof MilgrowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos': {
      id: '/metodos'
      path: '/metodos'
      fullPath: '/metodos'
      preLoaderRoute: typeof MetodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxi': {
      id: '/maxi'
      path: '/maxi'
      fullPath: '/maxi'
      preLoaderRoute: typeof MaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marco-boni': {
      id: '/marco-boni'
      path: '/marco-boni'
      fullPath: '/marco-boni'
      preLoaderRoute: typeof MarcoBoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livin': {
      id: '/livin'
      path: '/livin'
      fullPath: '/livin'
      preLoaderRoute: typeof LivinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kmillion': {
      id: '/kmillion'
      path: '/kmillion'
      fullPath: '/kmillion'
      preLoaderRoute: typeof KmillionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapyi': {
      id: '/kapyi'
      path: '/kapyi'
      fullPath: '/kapyi'
      preLoaderRoute: typeof KapyiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidive': {
      id: '/evidive'
      path: '/evidive'
      fullPath: '/evidive'
      preLoaderRoute: typeof EvidiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos/': {
      id: '/metodos/'
      path: '/'
      fullPath: '/metodos/'
      preLoaderRoute: typeof MetodosIndexRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/sistema-de-conteudo': {
      id: '/metodos/sistema-de-conteudo'
      path: '/sistema-de-conteudo'
      fullPath: '/metodos/sistema-de-conteudo'
      preLoaderRoute: typeof MetodosSistemaDeConteudoRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/presenca-digital': {
      id: '/metodos/presenca-digital'
      path: '/presenca-digital'
      fullPath: '/metodos/presenca-digital'
      preLoaderRoute: typeof MetodosPresencaDigitalRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/midia-ooh': {
      id: '/metodos/midia-ooh'
      path: '/midia-ooh'
      fullPath: '/metodos/midia-ooh'
      preLoaderRoute: typeof MetodosMidiaOohRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/midia-impressa': {
      id: '/metodos/midia-impressa'
      path: '/midia-impressa'
      fullPath: '/metodos/midia-impressa'
      preLoaderRoute: typeof MetodosMidiaImpressaRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/marketing-de-influencia': {
      id: '/metodos/marketing-de-influencia'
      path: '/marketing-de-influencia'
      fullPath: '/metodos/marketing-de-influencia'
      preLoaderRoute: typeof MetodosMarketingDeInfluenciaRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/metodos/estruturacao-de-marca': {
      id: '/metodos/estruturacao-de-marca'
      path: '/estruturacao-de-marca'
      fullPath: '/metodos/estruturacao-de-marca'
      preLoaderRoute: typeof MetodosEstruturacaoDeMarcaRouteImport
      parentRoute: typeof MetodosRoute
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MetodosRouteChildren {
  MetodosEstruturacaoDeMarcaRoute: typeof MetodosEstruturacaoDeMarcaRoute
  MetodosMarketingDeInfluenciaRoute: typeof MetodosMarketingDeInfluenciaRoute
  MetodosMidiaImpressaRoute: typeof MetodosMidiaImpressaRoute
  MetodosMidiaOohRoute: typeof MetodosMidiaOohRoute
  MetodosPresencaDigitalRoute: typeof MetodosPresencaDigitalRoute
  MetodosSistemaDeConteudoRoute: typeof MetodosSistemaDeConteudoRoute
  MetodosIndexRoute: typeof MetodosIndexRoute
}

const MetodosRouteChildren: MetodosRouteChildren = {
  MetodosEstruturacaoDeMarcaRoute: MetodosEstruturacaoDeMarcaRoute,
  MetodosMarketingDeInfluenciaRoute: MetodosMarketingDeInfluenciaRoute,
  MetodosMidiaImpressaRoute: MetodosMidiaImpressaRoute,
  MetodosMidiaOohRoute: MetodosMidiaOohRoute,
  MetodosPresencaDigitalRoute: MetodosPresencaDigitalRoute,
  MetodosSistemaDeConteudoRoute: MetodosSistemaDeConteudoRoute,
  MetodosIndexRoute: MetodosIndexRoute,
}

const MetodosRouteWithChildren =
  MetodosRoute._addFileChildren(MetodosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EvidiveRoute: EvidiveRoute,
  KapyiRoute: KapyiRoute,
  KmillionRoute: KmillionRoute,
  LivinRoute: LivinRoute,
  MarcoBoniRoute: MarcoBoniRoute,
  MaxiRoute: MaxiRoute,
  MetodosRoute: MetodosRouteWithChildren,
  MilgrowsRoute: MilgrowsRoute,
  NatraveRoute: NatraveRoute,
  SobreRoute: SobreRoute,
  SolidRoute: SolidRoute,
  SympliceRoute: SympliceRoute,
  Talk2buyRoute: Talk2buyRoute,
  TrabalhoRoute: TrabalhoRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
